# adminer доступен по адресу http://192.168.99.100:6060
# логин postgres, пароль root
# запуск контейнера docker-compose build сборка, docker-compose up запуск

version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 6060:8080